# version: "3.12"

services:
  backend:
    build: ./src/backend
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    env_file:
      - .env
    restart: always
    networks:
      - app-network

  frontend:
    build: ./src/frontend
    ports:
      - "${STREAMLIT_PORT}:${STREAMLIT_PORT}"
    env_file:
      - .env
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
